# Generated by Django 2.2.12 on 2021-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
